### PR TITLE
fix: better name to stop namespace conflict with Unity

### LINKED ISSUE #737: Naming collision for NetworkManager.SceneManager
**Describe the bug**
`NetworkManager.SceneManager` collides with `UnityEngine.SceneManagement.SceneManager` when used in child class of `NetworkManager`

**To Reproduce**
1. Create child class of `NetworkManager`
2. Use Unity's `SceneManager`
3. See error

**Expected behavior**
No naming collision for property

### PR DESCRIPTION
**Pull request by uweenukr**
fixes #737

### CODE REVIEW

**Comment by uweenukr** [comment]
How should we handle the fact that this is the second rename? Add another "FormerlySerializedAs"?

**Review by James-Frowen — APPROVED** [review]

**Comment by James-Frowen** [comment]
> How should we handle the fact that this is the second rename? Add another "FormerlySerializedAs"?

we should add a new `FormerlySerializedAs`


I think this also counts as a breaking change

**Comment by uweenukr** [comment]
If we add a second FormerlySerializedAs then its not breaking. I wasnt sure if having a second one even works.

**Comment by James-Frowen** [comment]
its still breaking via the code, if someone uses the old name they will have to change it to the new one

File: Assets/Mirage/Runtime/NetworkManager.cs [hunk 1]
```diff
@@ -16,7 +16,7 @@ public class NetworkManager : MonoBehaviour
         [FormerlySerializedAs("client")]
         public NetworkClient Client;
         [FormerlySerializedAs("sceneManager")]
-        public NetworkSceneManager SceneManager;
+        public NetworkSceneManager NetworkSceneManager;
```
Comment (James-Frowen) [inline Assets/Mirage/Runtime/NetworkManager.cs:19]:
```suggestion
        [FormerlySerializedAs("SceneManager")]
        public NetworkSceneManager NetworkSceneManager;
```
