### PR TITLE
fix: character spawner fix

### LINKED ISSUE #945: Rejoining server causes prefabs to become unregistered
**Describe the bug**
Joining a server, leaving, and then joining again causes prefabs to get unregistered and they can no longer be spawned, resulting in the client being thrown out of the server instantly. 

**Repro project**
[Mirage Issue.zip](https://github.com/MirageNet/Mirage/files/7219730/Mirage.Issue.zip)

**To Reproduce**
1. Open the attached project
2. Go into the SampleScene in the Scenes folder.
3. Make a build and run it.
4. Create a server in either Unity or the built client.
5. Join the server.
6. Leave the server
7. Join the server again
8. Observe the issue

**Expected behavior**
The user should be able to rejoin the server.

**Desktop (please complete the following information):**
* OS: Windows 10 64-bit
* Build target: Windows 64-bit
* Unity version: 2020.3.17
* Mirage version: 105.1.0

### PR DESCRIPTION
**Pull request by dragonslaya84**
character spawner was registering the player prefab in awake an during scene loads this wont ever register again. Need to change it on scene changes.

Fixes #945 

Signed-off-by: dragonslaya <dragonslaya.ss@gmail.com>

### CODE REVIEW

File: Assets/Mirage/Runtime/CharacterSpawner.cs [hunk 1]
```diff
@@ -100,6 +91,15 @@ private void OnServerStarted()
         /// <param name="sceneOperation">The type of scene load that happened.</param>
         public virtual void OnClientFinishedSceneChange(string scenePath, SceneOperation sceneOperation)
         {
+            if (ClientObjectManager != null)
+            {
+                ClientObjectManager.RegisterPrefab(PlayerPrefab);
```
Comment (James-Frowen) [inline Assets/Mirage/Runtime/CharacterSpawner.cs:96]: I think this would register the prefab multiple times, Might be better to register it once when the client starts

Comment (dragonslaya84) [reply Assets/Mirage/Runtime/CharacterSpawner.cs:96]: It currently registers everytime scene changes. Mirage itself calls register prefabs internally in clientobjectmanager. This is why i had to move this here. So we either need to change how mirage registers ro once in clientobjectmanager or we need to do this. I trace it and every time player bit join then disconnect and join it called register spawn in that class

File: Assets/Mirage/Runtime/CharacterSpawner.cs [hunk 2]
```diff
@@ -74,7 +74,7 @@ void OnDestroy()
             }
         }
 
-        private void OnClientConnected(INetworkPlayer player)
+        protected internal void OnClientConnected(INetworkPlayer player)
```
Comment (James-Frowen) [inline Assets/Mirage/Runtime/CharacterSpawner.cs:77]: can this just be `internal`?
```suggestion
        internal void OnClientConnected(INetworkPlayer player)
```
